version: "3.8"

services:
  ekzameno:
    image: omjadas/ekzameno:latest
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
